// coong/clinet-preact-vite/src/pages/main/index.tsx
import {PageProps} from 'src/types'
import {Counter} from './Counter'
import {getPosts} from './get-posts'
import {useQuery} from '@urql/preact'
import {Post} from './Post'
import {useMemo} from 'preact/hooks'

export const MainPage = (_: PageProps) => {
  const [result] = useQuery({query: getPosts})
  const postsData = result?.data?.posts

  const posts = useMemo(() => {
    if (Array.isArray(postsData)) {
      return postsData.map((post) => {
        return <Post {...post}></Post>
      })
    }
  }, [postsData])

  return (
    <div>
      {posts}
      <Counter />
      <Counter />
    </div>
  )
}

// coong/client-vite/src/pages/main/Index.tsx
import {defineComponent} from 'vue'
import {getPosts} from 'src/graphql'
import {useQuery} from '@urql/vue'

export const Main = defineComponent({
  setup() {
    const {data} = useQuery({query: getPosts})
    return () => (
      <div>
        {data.value?.posts.map((item) => {
          return (
            <div key={item.id}>
              <span>{item.title}</span>
              <span>{item.message}</span>
            </div>
          )
        })}
      </div>
    )
  },
})

export default Main
